<?php
class AdviseDealProcess extends BaseModel {
    public $is_open_name='';
    public function tableName()
    {
        return '{{advise_dealprocess}}'; // TODO: Change the autogenerated stub
    }
    /*** Returns the static model of the specified AR class. */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    /**  * 模型关联规则  */
    public function relations() {
        return array();
    }
    /*** 模型验证规则*/
    public function rules() {
      return $this->attributeRule();
    }
    /** * 属性标签 */
    public function attributeLabels() {
        return $this->getAttributeSet();
    }
    public function attributeSets() {
        return array(
        'id' => 'id',
        'code' => '编码',
        'deal_content'=>'处理情况',
        'deal_state'=>'处理说明',
        'deal_time'=>'跟进时间',
        'is_open'=>'是否公开',
        'is_open_name'=>'是否公开',
        'eid'=>'外部id',
        );
       

     //x2_scourse,id,code,value,subjectsetting,subpic,id,x2_scourse;id;code;value;subjectsetting;subpic;id;
    }
    
   /*public function picLabels() {
        return 'subpic';//图片或文件
    }  
   public  function pathLabels(){
       return 'articles';//文件存放路径
   }
  
   /* 用于列表查询使用，三个参数分别是  1 条件 2 是排序 三是或取值，格式 变量[：变量]*/
    public function keySelect(){
        return array('1','code','deal_content');
    }
    /*protected function afterFind(){//需要定义
      parent::afterFind();
      $this->is_open_name=($this->is_open==1) ?'是' : '否';

    }*/
    protected function beforeSave() {
      parent::beforeSave();
     $this->is_open_name=($this->is_open==1) ?'是' : '否';
      return true;
  }

}
   