<?php
class PersonTijiao extends BaseModel {
    public function tableName()
    {
        return '{{sendtousu}}'; // TODO: Change the autogenerated stub
    }
    /*** Returns the static model of the specified AR class. */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    /**  * 模型关联规则  */
    public function relations() {
        return array();
    }
    /*** 模型验证规则*/
    public function rules() {
      return $this->attributeRule();
    }
    /** * 属性标签 */
    public function attributeLabels() {
        return $this->getAttributeSet();
    }
    public function attributeSets() {
        return array(
        'id' => 'id',
        'code' => '编码:k',//:k是不能为空的意思
        'phone' => '手机号码:k',
        'type' => '投诉类别:k',
        'content'=>'投诉内容:k',
        'subpic' => '上传图片',
        'niming'=>'是否匿名:k',
        'huifang'=>'是否回访:k',
        );

     //x2_scourse,id,code,phone,type,subpic,id,x2_scourse;id;code;value;subjectsetting;subpic;id;
    }
    
   public function picLabels() {
        return 'subpic';//图片或文件
    }  
   public  function pathLabels(){
       return 'articles';//文件存放路径
   }
  
   /* 用于列表查询使用，三个参数分别是  1 条件 2 是排序 三是或取值，格式 变量[：变量]*/
    public function keySelect(){
        return array('1','type','id:phone');
    }
    
    

}
   