<?php
class proposal extends BaseModel {
    public function tableName()
    {
        return '{{proposal}}'; // TODO: Change the autogenerated stub
    }
    /*** Returns the static model of the specified AR class. */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    /**  * 模型关联规则  */
    public function relations() {
        return array();
    }
    /*** 模型验证规则*/
    public function rules() {
      return $this->attributeRule();
    }
    /** * 属性标签 */
    public function attributeLabels() {
        return $this->getAttributeSet();
    }
    public function attributeSets() {
        return array(
        'id' => 'id',
        'title' => '议案主题',
        'content' => '议案内容',
        'code' => '议案编号',
        'type' => '议案类型',
        'author' => '议案提交人（团队）',
        'author_contact' => '议案提交者联系方式',
        'countersignature1' => '联署人1',
        'countersignature2' => '联署人2',
        'countersignature3' => '联署人3',
        'countersignature4' => '联署人4',
        'countersignature5' => '联署人5',
        'countersignature6' => '联署人6',
        'countersignature7' => '联署人7',
        'countersignature8' => '联署人8',
        'submit_time' => '提交时间',
        'last_modified_time' => '最后修改时间',
        'workstate' => '议案状态',
        'image' => '议案附件',
        'is_order' => '是否处于提交状态',
        'is_judge' => '是否处于审核状态',
        'is_judge_show' => '是否在审核界面展出',
        'is_search' => '是否处于查询状态',
        'is_allocation' => '是否交办',
        'is_progress' => '是否跟进处理',
        'judge_time' => '审核时间',
        'up_time' => '今日开始时间',
        'end_time' => '今日结束时间',
        // 'result' => '审核结果',
        'company_name'=>'交办单位名称',
        'company_header'=>'交办单位负责人',
        'company_contact'=>'交办单位联系方式',
        'supervision_company'=>'监办单位',
        'supervision_contact'=>'监办单位联系方式',
        'allocation_remark'=>'交办备注',
        'suggestion' => '审核意见:k',
        'remark' => '备注',
        );
       

     //x2_scourse,id,code,value,subjectsetting,subpic,id,x2_scourse;id;code;value;subjectsetting;subpic;id;
    }
    
   public function picLabels() {
        return 'image';//图片或文件
    }  
   public  function pathLabels(){
       return 'articles';//文件存放路径
   }
  
   /* 用于列表查询使用，三个参数分别是  1 条件 2 是排序 三是或取值，格式 变量[：变量]*/
    public function keySelect(){
        return array('1','code','proposal_type');
    }

 


}
   